# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs:
  build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      -uses: actions/checkout
      -name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-